version: '3'
services:
 zookeeper:
  image: wurstmeister/zookeeper
  container_name: zookeeper
  restart: always
  logging:
   driver: json-file
   options:
     max-size: 1m
     max-file: '5'
  ports:
  - "2181:2181"

 kafka:
  image: wurstmeister/kafka
  container_name: kafka
  restart: always
  ports:
   - "9092:9092"
  depends_on:
   - zookeeper
  links:
   - zookeeper:zookeeper
  logging:
   driver: json-file
   options:
     max-size: 1m
     max-file: '5'
  environment :
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CREATE_TOPICS: "my_topic:2:1"